### ISSUE TITLE
Hydra shows no services or nodes

### ISSUE THREAD

**Issue by intermundos** [flywheelsports/hydra-cli#32]
Hello,

hydra-cli nodes or hydra-cli services returns an empty array.

Service is running as in example of hello-service. Followed every step. 

Can you please point out where should I look to fix this? 

Thank you in advance.

A

**Comment by cjus** [comment]
@intermundos what version of hydra-cli are you using and what platform are you running it on?

**Comment by intermundos** [comment]
hydra-cli version 1.3.6, Mac El Captain 10.11.3, iTerm2, Node 8.4.0, npm 5.4.1

**Comment by cjus** [comment]
@intermundos are you running Redis locally on your Mac? Also are your services running locally? If so, did you configure your service to point to the same Redis instance that Hydra-Cli is pointing to?

**Comment by intermundos** [comment]
That was the reason - bad config. After changing in config.json serviceIP and redis.url from 127.0.0.1 to localhost, everything works. 

Thanks a lot for help. 

Hydra looks very interesting for our new project. More questions to follow :)

**Comment by cjus** [comment]
@intermundos Glad to help!! If you think you might have more questions you should consider joining our slack channel ;-)

**Comment by intermundos** [comment]
I am in :)
