### ISSUE TITLE
Better error message when redis isn't configured

### ISSUE THREAD

**Issue by emadum** [flywheelsports/hydra-cli#7]
Currently it tries to call hgetall on a null value and throws a fatal.

**Comment by emadum** [comment]
Possibly use this module:
https://www.npmjs.com/package/diskusage

**Comment by cjus** [comment]
Addressed in commit: https://github.com/flywheelsports/hydra-cli/commit/570ffbf8ef70c41afae0c9c92cdcc355004700a2
